// State data for KARE calculator
const stateData = {
  Alabama: {
    state: "Alabama",
    license: "CNA/CMA",
    concatenate: "AlabamaCNA/CMA",
    payRate: 16,
    withOvertime: 24,
    overtimeCost: 6.96,
    realHourlyCost: 30.96,
    kareRate: 20.83,
    savings: 10.13,
  },
  Colorado: {
    state: "Colorado",
    license: "CNA/CMA",
    concatenate: "ColoradoCNA/CMA",
    payRate: 21.32,
    withOvertime: 31.98,
    overtimeCost: 9.27,
    realHourlyCost: 41.25,
    kareRate: 31.66,
    savings: 9.59,
  },
  Connecticut: {
    state: "Connecticut",
    license: "CNA/CMA",
    concatenate: "ConnecticutCNA/CMA",
    payRate: 24.51,
    withOvertime: 36.77,
    overtimeCost: 11.08,
    realHourlyCost: 47.85,
    kareRate: 32.54,
    savings: 15.31,
  },
  Delaware: {
    state: "Delaware",
    license: "CNA/CMA",
    concatenate: "DelawareCNA/CMA",
    payRate: 19.03,
    withOvertime: 28.54,
    overtimeCost: 8.6,
    realHourlyCost: 37.14,
    kareRate: 24.56,
    savings: 12.58,
  },
  Florida: {
    state: "Florida",
    license: "CNA/CMA",
    concatenate: "FloridaCNA/CMA",
    payRate: 15.76,
    withOvertime: 23.65,
    overtimeCost: 7.13,
    realHourlyCost: 30.79,
    kareRate: 19.32,
    savings: 11.47,
  },
  Georgia: {
    state: "Georgia",
    license: "CNA/CMA",
    concatenate: "GeorgiaCNA/CMA",
    payRate: 15.55,
    withOvertime: 23.32,
    overtimeCost: 7.03,
    realHourlyCost: 30.35,
    kareRate: 19.27,
    savings: 11.08,
  },
  Hawaii: {
    state: "Hawaii",
    license: "CNA/CMA",
    concatenate: "HawaiiCNA/CMA",
    payRate: 26.08,
    withOvertime: 39.12,
    overtimeCost: 11.79,
    realHourlyCost: 50.91,
    kareRate: 33.5,
    savings: 17.41,
  },
  Idaho: {
    state: "Idaho",
    license: "CNA/CMA",
    concatenate: "IdahoCNA/CMA",
    payRate: 15.26,
    withOvertime: 22.89,
    overtimeCost: 6.9,
    realHourlyCost: 29.79,
    kareRate: 20.03,
    savings: 9.76,
  },
  Illinois: {
    state: "Illinois",
    license: "CNA/CMA",
    concatenate: "IllinoisCNA/CMA",
    payRate: 17.64,
    withOvertime: 26.46,
    overtimeCost: 7.98,
    realHourlyCost: 34.44,
    kareRate: 22.66,
    savings: 11.78,
  },
  Indiana: {
    state: "Indiana",
    license: "CNA/CMA",
    concatenate: "IndianaCNA/CMA",
    payRate: 16.72,
    withOvertime: 25.08,
    overtimeCost: 7.58,
    realHourlyCost: 32.66,
    kareRate: 21.62,
    savings: 11.04,
  },
  Iowa: {
    state: "Iowa",
    license: "CNA/CMA",
    concatenate: "IowaCNA/CMA",
    payRate: 17.17,
    withOvertime: 25.76,
    overtimeCost: 7.79,
    realHourlyCost: 33.55,
    kareRate: 22.88,
    savings: 10.67,
  },
  Kansas: {
    state: "Kansas",
    license: "CNA/CMA",
    concatenate: "KansasCNA/CMA",
    payRate: 15.71,
    withOvertime: 23.57,
    overtimeCost: 7.13,
    realHourlyCost: 30.7,
    kareRate: 20.28,
    savings: 10.42,
  },
  Kentucky: {
    state: "Kentucky",
    license: "CNA/CMA",
    concatenate: "KentuckyCNA/CMA",
    payRate: 15.89,
    withOvertime: 23.83,
    overtimeCost: 7.2,
    realHourlyCost: 30.85,
    kareRate: 19.48,
    savings: 11.37,
  },
  Louisiana: {
    state: "Louisiana",
    license: "CNA/CMA",
    concatenate: "LouisianaCNA/CMA",
    payRate: 15.27,
    withOvertime: 22.9,
    overtimeCost: 6.9,
    realHourlyCost: 29.8,
    kareRate: 19.43,
    savings: 10.37,
  },
  Maine: {
    state: "Maine",
    license: "CNA/CMA",
    concatenate: "MaineCNA/CMA",
    payRate: 18.17,
    withOvertime: 27.26,
    overtimeCost: 8.23,
    realHourlyCost: 35.49,
    kareRate: 22.85,
    savings: 12.64,
  },
  Maryland: {
    state: "Maryland",
    license: "CNA/CMA",
    concatenate: "MarylandCNA/CMA",
    payRate: 21.91,
    withOvertime: 32.87,
    overtimeCost: 9.93,
    realHourlyCost: 42.8,
    kareRate: 30.43,
    savings: 12.37,
  },
  Massachusetts: {
    state: "Massachusetts",
    license: "CNA/CMA",
    concatenate: "MassachusettsCNA/CMA",
    payRate: 25.75,
    withOvertime: 38.63,
    overtimeCost: 11.68,
    realHourlyCost: 50.31,
    kareRate: 34.46,
    savings: 15.85,
  },
  Michigan: {
    state: "Michigan",
    license: "CNA/CMA",
    concatenate: "MichiganCNA/CMA",
    payRate: 17.22,
    withOvertime: 25.84,
    overtimeCost: 7.82,
    realHourlyCost: 33.65,
    kareRate: 23.44,
    savings: 10.21,
  },
  Minnesota: {
    state: "Minnesota",
    license: "CNA/CMA",
    concatenate: "MinnesotaCNA/CMA",
    payRate: 19.45,
    withOvertime: 29.18,
    overtimeCost: 8.88,
    realHourlyCost: 38.06,
    kareRate: 27.13,
    savings: 10.93,
  },
  Mississippi: {
    state: "Mississippi",
    license: "CNA/CMA",
    concatenate: "MississippiCNA/CMA",
    payRate: 14.43,
    withOvertime: 21.64,
    overtimeCost: 6.53,
    realHourlyCost: 28.17,
    kareRate: 17.64,
    savings: 10.53,
  },
  Missouri: {
    state: "Missouri",
    license: "CNA/CMA",
    concatenate: "MissouriCNA/CMA",
    payRate: 15.35,
    withOvertime: 23.03,
    overtimeCost: 6.97,
    realHourlyCost: 30.0,
    kareRate: 19.3,
    savings: 10.7,
  },
  Montana: {
    state: "Montana",
    license: "CNA/CMA",
    concatenate: "MontanaCNA/CMA",
    payRate: 15.61,
    withOvertime: 23.41,
    overtimeCost: 7.07,
    realHourlyCost: 30.1,
    kareRate: 19.96,
    savings: 10.14,
  },
  Nebraska: {
    state: "Nebraska",
    license: "CNA/CMA",
    concatenate: "NebraskaCNA/CMA",
    payRate: 15.95,
    withOvertime: 23.92,
    overtimeCost: 7.29,
    realHourlyCost: 31.24,
    kareRate: 20.5,
    savings: 10.74,
  },
  Nevada: {
    state: "Nevada",
    license: "CNA/CMA",
    concatenate: "NevadaCNA/CMA",
    payRate: 19.5,
    withOvertime: 29.25,
    overtimeCost: 8.85,
    realHourlyCost: 38.1,
    kareRate: 25.5,
    savings: 12.6,
  },
  NewHampshire: {
    state: "New Hampshire",
    license: "CNA/CMA",
    concatenate: "NewHampshireCNA/CMA",
    payRate: 18.5,
    withOvertime: 27.75,
    overtimeCost: 8.4,
    realHourlyCost: 35.9,
    kareRate: 24.5,
    savings: 11.4,
  },
  NewJersey: {
    state: "New Jersey",
    license: "CNA/CMA",
    concatenate: "NewJerseyCNA/CMA",
    payRate: 22.5,
    withOvertime: 33.75,
    overtimeCost: 10.2,
    realHourlyCost: 43.95,
    kareRate: 30.5,
    savings: 13.45,
  },
  NewMexico: {
    state: "New Mexico",
    license: "CNA/CMA",
    concatenate: "NewMexicoCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  NewYork: {
    state: "New York",
    license: "CNA/CMA",
    concatenate: "NewYorkCNA/CMA",
    payRate: 23.5,
    withOvertime: 35.25,
    overtimeCost: 10.65,
    realHourlyCost: 45.9,
    kareRate: 31.5,
    savings: 14.4,
  },
  NorthCarolina: {
    state: "North Carolina",
    license: "CNA/CMA",
    concatenate: "NorthCarolinaCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  NorthDakota: {
    state: "North Dakota",
    license: "CNA/CMA",
    concatenate: "NorthDakotaCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  },
  Ohio: {
    state: "Ohio",
    license: "CNA/CMA",
    concatenate: "OhioCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  },
  Oklahoma: {
    state: "Oklahoma",
    license: "CNA/CMA",
    concatenate: "OklahomaCNA/CMA",
    payRate: 15.5,
    withOvertime: 23.25,
    overtimeCost: 7.05,
    realHourlyCost: 30.3,
    kareRate: 20.5,
    savings: 9.8,
  },
  Oregon: {
    state: "Oregon",
    license: "CNA/CMA",
    concatenate: "OregonCNA/CMA",
    payRate: 20.5,
    withOvertime: 30.75,
    overtimeCost: 9.3,
    realHourlyCost: 39.9,
    kareRate: 26.5,
    savings: 13.4,
  },
  Pennsylvania: {
    state: "Pennsylvania",
    license: "CNA/CMA",
    concatenate: "PennsylvaniaCNA/CMA",
    payRate: 18.5,
    withOvertime: 27.75,
    overtimeCost: 8.4,
    realHourlyCost: 35.9,
    kareRate: 24.5,
    savings: 11.4,
  },
  RhodeIsland: {
    state: "Rhode Island",
    license: "CNA/CMA",
    concatenate: "RhodeIslandCNA/CMA",
    payRate: 19.5,
    withOvertime: 29.25,
    overtimeCost: 8.85,
    realHourlyCost: 38.1,
    kareRate: 25.5,
    savings: 12.6,
  },
  SouthCarolina: {
    state: "South Carolina",
    license: "CNA/CMA",
    concatenate: "SouthCarolinaCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  SouthDakota: {
    state: "South Dakota",
    license: "CNA/CMA",
    concatenate: "SouthDakotaCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  Tennessee: {
    state: "Tennessee",
    license: "CNA/CMA",
    concatenate: "TennesseeCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  Texas: {
    state: "Texas",
    license: "CNA/CMA",
    concatenate: "TexasCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  Utah: {
    state: "Utah",
    license: "CNA/CMA",
    concatenate: "UtahCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  },
  Vermont: {
    state: "Vermont",
    license: "CNA/CMA",
    concatenate: "VermontCNA/CMA",
    payRate: 18.5,
    withOvertime: 27.75,
    overtimeCost: 8.4,
    realHourlyCost: 35.9,
    kareRate: 24.5,
    savings: 11.4,
  },
  Virginia: {
    state: "Virginia",
    license: "CNA/CMA",
    concatenate: "VirginiaCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  },
  Washington: {
    state: "Washington",
    license: "CNA/CMA",
    concatenate: "WashingtonCNA/CMA",
    payRate: 20.5,
    withOvertime: 30.75,
    overtimeCost: 9.3,
    realHourlyCost: 39.9,
    kareRate: 26.5,
    savings: 13.4,
  },
  WestVirginia: {
    state: "West Virginia",
    license: "CNA/CMA",
    concatenate: "WestVirginiaCNA/CMA",
    payRate: 16.5,
    withOvertime: 24.75,
    overtimeCost: 7.5,
    realHourlyCost: 32.25,
    kareRate: 21.5,
    savings: 10.75,
  },
  Wisconsin: {
    state: "Wisconsin",
    license: "CNA/CMA",
    concatenate: "WisconsinCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  },
  Wyoming: {
    state: "Wyoming",
    license: "CNA/CMA",
    concatenate: "WyomingCNA/CMA",
    payRate: 17.5,
    withOvertime: 26.25,
    overtimeCost: 7.95,
    realHourlyCost: 34.2,
    kareRate: 22.5,
    savings: 11.7,
  }
};

// Export the data
export { stateData }; 